@startuml

(*) -->  "получение с конфига пути к бинарникам Scade"
if "путь к бинарникам валиден?"
    --> [да] "получение пути к директории тестов"
    if "путь к директории тестов валиден?"
      --> [да] "рекурсивный поиск всех текстовых файлов 
      содержащих RAW в наименовании"
      if "найден хобя бы один файл?"
        --> [да] "формирование файла с путями 
        всех найденных результатов"
        --> "запуск qtereport"
        --> [выход] (*)
      else
        --> [нет] "логирование ошибки"
      endif
    else
        --> [нет] "логирование ошибки"
    endif
else 
    --> [нет] "логирование ошибки"
    --> [выход] (*)
end if


@enduml