@startuml

:считать с конфига путь к Scade;
:пропатчить Scade;
:считать с конфига путь к тестовым проектам;
:найти отчеты прогона тестовых проектов;
:сформировать файл с путями к отчетам тестовых проектов;
:запустить qtereport;

@enduml
